export const ActionTypes =  {
    SET_BANNERS             :   "SET_BANNERS", 
    SET_TOP_BOOKED_TESTS    :   "SET_TOP_BOOKED_TESTS", 
    SET_TEST_CART_LIST      :   "SET_TEST_CART_LIST", 
    SET_TEST_DETAILS        :   "SET_TEST_DETAILS", 
    SET_ALL_TEST_DETAILS    :   "SET_ALL_TEST_DETAILS", 
    REMOVE_TEST_DETAILS     :   "REMOVE_TEST_DETAILS",
    ADD_TO_CART             :   "ADD_TO_CART",
    REMOVE_FROM_CART        :   "REMOVE_FROM_CART"
}