// export const URL = "http://localhost:8080/ADLWebapp"
export const URL = "http://adladmin.pixel-studios.net"

export const API_URL = {
    ASSETS                : `${URL}/storage/app/`,
    BANNERS               : `${URL}/public/api/banners`,
    TOP_BOOKED_TEST       : `${URL}/public/api/topBookedTest`,
    TEST_DETAILS          : `${URL}/api/test/`,
    TEST_LISTS            : `${URL}/api/test-list`,
    BANNER_FROM           : `${URL}/api/bannerContactForm`,
    NEWS_AND_EVENTS       : `${URL}/api/newsAndEvents`,
    REGISTER              : `${URL}/api/register`,
    LOGIN              : `${URL}/api/login`,
    UPDATE_BILLING_DETAILS: `${URL}/api/update-billing-details`,
    SAVE_THE_ORDER: `${URL}/api/save-payment-order`,
    GET_CUSTOMER_INFO: `${URL}/api/customer/`,
    PACKAGES_LIST: `${URL}/api/packages`,
    PATIENTS_CONSUMERS: `${URL}/api/patients-consumers`, 
    FEEDBACKS: `${URL}/api/feedback`, 
    FAQ: `${URL}/api/faq`, 
    HOSPITAL_LAB_MANAGEMENT: `${URL}/api/hospital-lab-management`, 
    CLINICAL_LAB_MANAGEMENT: `${URL}/api/clinical-lab-management`, 
    RESEARCH: `${URL}/api/research`,  
    HEALTHCHECKUP_FOR_EMPLOYEES: `${URL}/api/healthcheckup-for-employees`,   
    BOOK_AN_APPOINTMENT: `${URL}/api/book-an-appointment`,
    UPDATE_MY_PROFILE: `${URL}/api/update-customer/`,    
    GET_MY_ORDERS: `${URL}/api/get-orders/`,    
    CHANGE_MY_PASSWORD: `${URL}/api/change-my-password/`,     
    CANCEL_MY_ORDER: `${URL}/api/cancel-my-order/`,      
}